name: entities_repository
description: A repository that handles character, location and episode related requests.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  coverage: ^1.1.0
  http_mock_adapter: ^0.3.2
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0

dependencies:
  rimo_api:
    path: ../rimo_api
