name: df_api
description: Dialogflow gRPC API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
dependencies: 
  googleapis: ^8.1.0
  googleapis_auth: ^1.3.0
  uuid: ^3.0.6
